config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'searches#search'
  root 'searches#search'
  resources :authors
  resources :videos
  resources :games
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  searchkick

  def search_data
    {
      full_name: full_name,
      bio: bio
    }
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :bio)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<article class="search-result row">
  <div class="col-xs-12 col-sm-12 col-md-3">
    <a href="#" title="Lorem ipsum" class="thumbnail"><img src="http://via.placeholder.com/250x140" alt="Lorem ipsum" /></a>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-2">
    <ul class="meta-search">
      <li><i class="glyphicon glyphicon-calendar"></i> <span><%= author.created_at.strftime("%B %d, %Y") %></span></li>
    </ul>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
    <h3><a href="#" title=""><%= author.full_name %></a></h3>
    <p><%= author.bio.truncate(250) %></p>
    <span class="plus"><a href="#" title="Lorem ipsum"><i class="glyphicon glyphicon-plus"></i></a></span>
  </div>
  <span class="clearfix borda"></span>
</article>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.first_name %></td>
        <td><%= author.last_name %></td>
        <td><%= author.bio %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @author.bio %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>