config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'searches#search'
  root 'searches#search'
  resources :authors
  resources :videos
  resources :games
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
  searchkick

  def search_data
    {
      title: title,
      description: description
    }
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :description)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<article class="search-result row">
  <div class="col-xs-12 col-sm-12 col-md-3">
    <a href="#" title="Lorem ipsum" class="thumbnail"><img src="http://via.placeholder.com/250x140" alt="Lorem ipsum" /></a>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-2">
    <ul class="meta-search">
      <li><i class="glyphicon glyphicon-calendar"></i> <span><%= video.created_at.strftime("%B %d, %Y") %></span></li>
    </ul>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
    <h3><a href="#" title=""><%= video.title %></a></h3>
    <p><%= video.description.truncate(250) %></p>
    <span class="plus"><a href="#" title="Lorem ipsum"><i class="glyphicon glyphicon-plus"></i></a></span>
  </div>
  <span class="clearfix borda"></span>
</article>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>