config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'searches#search'
  root 'searches#search'
  resources :authors
  resources :videos
  resources :games
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  searchkick

  def search_data
    {
      name: name,
      description: description
    }
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<article class="search-result row">
  <div class="col-xs-12 col-sm-12 col-md-3">
    <a href="#" title="Lorem ipsum" class="thumbnail"><img src="http://via.placeholder.com/250x140" alt="Lorem ipsum" /></a>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-2">
    <ul class="meta-search">
      <li><i class="glyphicon glyphicon-calendar"></i> <span><%= game.created_at.strftime("%B %d, %Y") %></span></li>
    </ul>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-7 excerpet">
    <h3><a href="#" title=""><%= game.name %></a></h3>
    <p><%= game.description.truncate(250) %></p>
    <span class="plus"><a href="#" title="Lorem ipsum"><i class="glyphicon glyphicon-plus"></i></a></span>
  </div>
  <span class="clearfix borda"></span>
</article>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.description %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>